FROM python:3.11-slim

WORKDIR /opt/camera

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY config ./config
COPY scripts ./scripts
COPY sample-data ./sample-data
COPY output ./output

RUN chmod +x ./scripts/start.sh

EXPOSE 8081

CMD ["./scripts/start.sh"]