# Use the official lightweight NGINX image
FROM nginx:alpine

# remove default nginx page
RUN rm /usr/share/nginx/html/index.html

# copy our web page
COPY resources/web/index.html /usr/share/nginx/html/index.html

# Expose port
EXPOSE 80

# Run nginx
CMD ["nginx", "-g", "daemon off;"]
