apiVersion: v1
kind: ConfigMap
metadata:
  name: camera-config
  namespace: imgest-mesh
data:
  camera-config.yaml: |
    service_name: camera
    mode: demo-images

    status:
      host: 0.0.0.0
      port: 8081

    capture:
      interval_seconds: 2
      max_frames: 0

    input:
      bmp_directory: /opt/camera/bmp-input

    output:
      directory: /opt/camera/output
      filename_prefix: frame

    storage:
      max_frames: 20
