FROM python:3.11-slim

WORKDIR /opt/inference

ARG SKIP_SSL_VERIFY=false

COPY requirements.txt .
RUN if [ "$SKIP_SSL_VERIFY" = "true" ]; then \
      pip install --no-cache-dir \
        --trusted-host pypi.org \
        --trusted-host files.pythonhosted.org \
        -r requirements.txt; \
    else \
      pip install --no-cache-dir -r requirements.txt; \
    fi

COPY app ./app
COPY config ./config
COPY scripts ./scripts
COPY models ./models

RUN mkdir -p /opt/inference/input /opt/inference/output/json /opt/inference/output/images
RUN sed -i 's/\r$//' scripts/start.sh && chmod +x ./scripts/start.sh

EXPOSE 8083

CMD ["./scripts/start.sh"]