FROM nginxinc/nginx-unprivileged:stable-alpine

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy site content
COPY index.html /usr/share/nginx/html/index.html
COPY t3-imgest-mesh.png /usr/share/nginx/html/t3-imgest-mesh.png

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
